### ISSUE TITLE
Add to https://caddyserver.com/download

### ISSUE THREAD

**Issue by ajusa** [greenpau/caddy-systemd#3]
Not sure what configuration is required to do this, but when I ran `caddy add-package github.com/greenpau/caddy-systemd` I got `github.com/greenpau/caddy-systemd is not a registered Caddy module package path`. Other modules written by you (caddy-security and caddy-git) seem to be listed on that page.

**Comment by greenpau** [comment]
@ajusa , this module is not yet ready for prime time.
